
export const biologyTopics = [
    // Grade 10
    'LIVING ORGANISMS AND LIFE PROCESSES',
    'CELL STRUCTURE AND ORGANISATION',
    'ENZYMES',
    'NUTRIENTS',
    'NUTRITION IN PLANTS',
    'SAPROPHYTIC NUTRITION',
    'NUTRITION IN ANIMALS',
    'RESPIRATORY SYSTEM',
    'HEALTH',
    // Grade 11
    'TRANSPORT AND STORAGE IN PLANTS',
    'TRANSPORT IN MAN',
    'EXCRETION',
    'HOMEOSTASIS AND OSMOREGULATION',
    'THE ENDOCRINE SYSTEM',
    'THE NERVOUS SYSTEM AND SENSE ORGANS',
    'THE SKELETON AND LOCOMOTION',
    'TROPIC AND TAXIC RESPONSES',
    'GROWTH AND DEVELOPMENT',
    // Grade 12
    'ASEXUAL REPRODUCTION',
    'SEXUAL REPRODUCTION IN FLOWERING PLANTS',
    'REPRODUCTION IN ANIMALS',
    'GENETICS',
    'CLASSIFICATION OF PLANTS AND ANIMALS',
    'THE SOIL',
    'ECOLOGY',
];
