
export const subjects = [
  'MATHS',
  'SCIENCE',
  'BIOLOGY',
  'ENGLISH',
  'RELIGIOUS EDUCATION',
  'CIVIC EDUCATION',
  'GEOGRAPHY',
  'COMMERCE',
  'PRINCIPLES OF ACC.',
  'ADDMA',
  'PURE CHEMISTRY',
  'PURE PHYSICS',
];
